/**
 * Webpack config for Google Apps Script project.
 * 
 * - Automatically bundles all .js files in /src to /build for clasp push
 * - Final HTML is generated by scripts/inject_sidebar.sh (not Webpack plugins)
 */

const path = require("path");
const fs = require("fs");
const GasPlugin = require("gas-webpack-plugin");
const webpack = require("webpack");

console.log("🛠️  Using webpack.config.js with dynamic entry discovery");

// Auto-generate entry object for all .js files in src/
const srcDir = path.resolve(__dirname, "build/ts");
const entry = {};

// Only bundle files other than FilterUICode.js - we leave this raw -- better integration w/ GAS
fs.readdirSync(srcDir)
   .filter(file =>
      file.endsWith(".js") &&
      file !== "FilterUICode.js" &&
      file !== "Code.js"     // 👈 explicitly exclude Code.js
    )
  .forEach(file => {
    const name = path.basename(file, ".js");
    entry[name] = path.join(srcDir, file);
  });




module.exports = {
  mode: "development",
  context: __dirname,
  entry,
  output: {
    path: path.resolve(__dirname, "build"),
    filename: "[name].js",
  },
  resolve: {
    extensions: [".ts", ".js"],
  },
plugins: [ ],
  devtool: false,
};

